### ISSUE TITLE
Issue generating Java representation of VRP ReadRefundAccount enum

### ISSUE THREAD

**Issue by dbadham-fr** [OpenBankingUK/read-write-api-specs#89]
The [ReadRefundAccount](https://github.com/OpenBankingUK/read-write-api-specs/blob/92bebfabc65bf115481c22f230af0ce372f23a01/dist/openapi/vrp-openapi.yaml#L767) defined in the VRP spec is an enum which supports a Yes or No value.
This is causing an issue when we use the `openapi-generator-maven-plugin` to generate Java code for this type.

The generator is interpreting the yml Yes/No as boolean values and mapping them to true/false, which causes the Java code to be produced as follows:
```
public enum ReadRefundAccountEnum {
    TRUE("true"),
    FALSE("false");
...
}
```

A fix for this is to quote the "Yes" and "No" values in the yml schema and the codegen produces the correct output. As Yes and No are valid representations of boolean in yml, then I think for safety they should be quoted so they are not misinterpreted. The definition would then look like this:
```
ReadRefundAccount:
  type: string
  enum:
    - "Yes"
    - "No"
  description: >
    Indicates whether information about RefundAccount should be included in the payment response.
```

Looking at the [Open API examples](https://swagger.io/specification/?sbsearch=Enumeration#server-variable-object), we see they do the same thing for the port enumeration, quoting the port values. 

I would really appreciate it if someone can review the above and apply the fix I have suggested please.
